### ISSUE TITLE
Manual Creation steps incorrect

### ISSUE THREAD

**Issue by apollyonbob** [kkukshtel/Depot#16]
From your example, this isn't correct JSON -
{
    sheets:[]
}

Whoops! The property name needs to be in quotes. Sure enough, it doesn't open. Side note here - probably should have some kind of error instead of just a blank editor.

This is what your default creates, for the record, though I'm sure you know haha.
{
    "sheets":[]
}

**Comment by kkukshtel** [comment]
Ah sorry! Definitely messed this up 🙃

You can submit a PR of just changing the readme if you want or I can fix it quickly :)
