### ISSUE TITLE
Toggle visibility of editor buttons 

### ISSUE THREAD

**Issue by L3v3L** [kkukshtel/Depot#19]
## Problem
Sometimes you just want to navigate through the data, and having the editor buttons always visibile becomes very distracting.

## Proposal
Have a way to toggle the editor button visibility.

**Comment by kkukshtel** [comment]
Definitely agree with this! Got an issue to track a few things on this here: 

https://github.com/kkukshtel/Depot/issues/4

Add some comments there if you've got specific things you'd be looking for that aren't yet listed.

**Comment by kkukshtel** [comment]
@L3v3L Added in fix for this in the latest version directly. I felt like was time haha:
![image](https://user-images.githubusercontent.com/7715279/105914277-23aefd00-5ffc-11eb-8e19-0523e8def5af.png)
