### ISSUE TITLE
Can't create a new sheet in a new Depot file in 1.3.0

### ISSUE THREAD

**Issue by invicticide** [kkukshtel/Depot#27]
In 1.3.0 if I create a new Depot file and click the New Sheet button, the button disappears and no other UI appears. No interactions are available in the Depot editor. If I open the Depot file as text, I see what seems to be a correct file stub: `{ "sheets": []}` so I don't think the file is broken, but something is up with the editor.

New file opened in Depot editor:

![before](https://user-images.githubusercontent.com/5454687/97788859-3fc80d00-1b79-11eb-911f-32fe001e1280.png)

I click the New Sheet button, and now it looks like this:

![after](https://user-images.githubusercontent.com/5454687/97788858-3fc80d00-1b79-11eb-9213-77ca4ccfa973.png)

I didn't see anything that looks relevant in any of the logs views in the Output panel. I rolled the extension back to 1.2.1 and everything works just fine there. FWIW I'm on VS Code 1.50.1 on Ubuntu 20.04.1.

**Comment by kkukshtel** [comment]
@invicticide Thanks for picking this up! Just resolved this in 1.3.1  with https://github.com/kkukshtel/Depot/commit/9441f865c5683ff91675280826e204bbde6b61c8 and pushed an update. Let me know if you still have issues!
